name: Update Counter
on:
  schedule:
    - cron: '0 * * * *' # Update setiap jam
  workflow_dispatch: # Memungkinkan trigger manual

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Beri akses write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Count
        id: count
        uses: juliangruber/unique-id-action@v1
        with:
          key: ${{ github.repository }}-visits

      - name: Update SVG
        run: |
          # Format count ke hex 4 digit
          HEX_COUNT=$(printf '%04x' ${{ steps.count.outputs.count }})
          sed -i "s/0x[0-9a-fA-F]\{4\}/0x${HEX_COUNT}/g" .github.io/counter.svg

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🔄 Update visitor counter: 0x${HEX_COUNT}"
          branch: master
          file_pattern: .github.io/counter.svg
