name: Update Profile Animation
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-profile-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Animation
        run: |
          mkdir -p dist
          echo "<!-- Updated: $(date '+%Y-%m-%d %H:%M:%S') -->" > dist/profile-animation.svg
          # Tambahkan konten SVG disini

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update profile animation [skip ci]"
