name: Generate Animated Profile
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0  # Penting untuk mendapatkan semua branch
          token: ${{ secrets.PAT_TOKEN }} # Ganti dengan Personal Access Token

      - name: Setup Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Generate SVG
        run: |
          # Script generate SVG sebelumnya...

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT_TOKEN }} # Harus sama dengan token checkout
          publish_dir: ./dist
          publish_branch: output
          keep_files: true
          force_orphan: true  # Untuk menghindari conflict history
          enable_jekyll: false
