name: Deploy Animated Profile
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-profile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: .github.io

      - name: Generate Dynamic Content
        run: |
          CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          HEX_COUNT=$(shuf -i 1000-9999 -n 1 | awk '{printf "0x%04x\n", $1}')
          
          # Generate random code lines
          GENERATED_CODE=$(awk -v len=40 -v lines=30 'BEGIN {
            chars="ABCDEFGHIJKLMNOPQRSTUVWXYZ$%&/#1234567890{}[]=+-_"
            commands="git commit npm start sudo apt-get docker build curl -X GET"
            split(commands, cmd)
            for(i=1;i<=lines;i++){
              if(i%5==0) printf "<tspan x='20' dy='20' fill='#4fdfff'>" cmd[int(rand()*5)+1] "</tspan>\n"
              else {
                str=""
                for(j=0;j<len;j++) str = str substr(chars, int(rand()*length(chars))+1,1)
                printf "<tspan x='20' dy='20'>%s</tspan>\n", str
              }
            }
          }')

          # Generate SVG
          cat > .github.io/profile.svg <<EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="0 0 1200 800">
            <defs>
              <linearGradient id="cyberGrad">
                <stop offset="0%" stop-color="#0a0a0a"/>
                <stop offset="100%" stop-color="#001a0f"/>
              </linearGradient>
              
              <filter id="glitch">
                <feTurbulence baseFrequency="0.01" numOctaves="2"/>
                <feDisplacementMap in="SourceGraphic" scale="8"/>
              </filter>
            </defs>

            <!-- Left Code Panel -->
            <g transform="translate(50 500)">
              <rect width="300" height="400" fill="url(#cyberGrad)" rx="10"/>
              <g font-family="monospace" font-size="14" fill="#00ff9d">
                ${GENERATED_CODE}
                <animateTransform attributeName="transform" 
                  type="translate" from="0 0" to="0 -400" 
                  dur="20s" repeatCount="indefinite"/>
              </g>
            </g>

            <!-- Center Content -->
            <g transform="translate(450 300)">
              <rect width="300" height="200" rx="15" fill="#1a1a1a"/>
              <text text-anchor="middle" font-size="48" fill="#00ff9d" filter="url(#glitch)">
                <tspan x="150" y="100">Code</tspan>
                <tspan x="150" y="160">Enthusiast</tspan>
                <animate attributeName="filter" values="url(#glitch);none" dur="0.3s" repeatCount="indefinite"/>
              </text>
              <text x="150" y="200" text-anchor="middle" font-size="24" fill="#fff" font-family="monospace">
                >_ I am programmer
              </text>
            </g>

            <!-- Visit Counter -->
            <g transform="translate(900 100)">
              <rect width="200" height="80" rx="15" fill="#1a1a1a"/>
              <circle cx="40" cy="40" r="15" fill="#00ff9d">
                <animate attributeName="r" values="15;12;15" dur="1.5s" repeatCount="indefinite"/>
              </circle>
              <text x="100" y="50" font-size="24" fill="#00ff9d">
                ${HEX_COUNT}
                <tspan x="100" dy="25" font-size="14" fill="#ccc">VISITORS</tspan>
              </text>
            </g>

            <text x="20" y="780" font-size="12" fill="#fff">
              Last update: ${CURRENT_DATE}
            </text>
          </svg>
          EOF

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .github.io
          publish_branch: output
          keep_files: true
          commit_message: "Update profile animation [skip ci]"

  update-readme:
    needs: generate-profile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        run: |
          PROFILE_URL="https://raw.githubusercontent.com/${{ github.repository }}/output/profile.svg"
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          
          echo -e "# My Profile\n[![Animated Profile]($PROFILE_URL)]($PROFILE_URL)" > README.md
          echo -e "\n_Last updated: ${TIMESTAMP}_" >> README.md

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update README [skip ci]"
          branch: master
