name: Update Profile Animation
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-profile-animation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Animated SVG
        run: |
          mkdir -p dist
          CURRENT_DATE=$(date '+%Y-%m-%d %H:%M:%S')
          cat > dist/profile-animation.svg <<EOF
          <svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 200 200">
            <style>
              .text { font: 12px sans-serif; fill: #333; }
              .circle { fill: none; stroke: #4a90e2; stroke-width: 3; }
            </style>
            
            <!-- Animated rotating circle -->
            <g transform="translate(100,100)">
              <circle class="circle" r="50">
                <animateTransform
                  attributeName="transform"
                  type="rotate"
                  from="0"
                  to="360"
                  dur="4s"
                  repeatCount="indefinite"/>
              </circle>
            </g>
            
            <!-- Text with update time -->
            <text x="50%" y="190" class="text" text-anchor="middle">
              Last Updated: $CURRENT_DATE
            </text>
            
            <!-- Blinking dot animation -->
            <circle cx="160" cy="40" r="5" fill="#ff4757">
              <animate attributeName="opacity" values="0;1;0" dur="2s" repeatCount="indefinite"/>
            </circle>
          </svg>
          EOF

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          keep_files: true  # Penting: mempertahankan file yang sudah ada
          commit_message: "Update profile animation [skip ci]"
